input_data_path: "data/raw/tmp.csv"
output_data_path: "models/predictions.csv"
pipeline_path: "models/transformer.pkl"
model_path: "models/model.pkl"
feature_list:
  - "sex"
  - "cp"
  - "fbs"
  - "restecg"
  - "exang"
  - "slope"
  - "ca"
  - "thal"
  - "age"
  - "trestbps"
  - "chol"
  - "thalach"
  - "oldpeak"