
name: hw1

on:
  push:
    branches: [ homework1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      working-directory: ./ml_project
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      working-directory: ./ml_project
      run: |
        flake8
    - name: Test with pytest
      working-directory: ./ml_project
      run: |
        pytest -v
